### ISSUE TITLE
Problem on first startup

### ISSUE THREAD

**Issue by vdeville** [MyTheValentinus/myjdownloader-docker#2]
Since the last big update of this docker, the docker crash at the creation.

I don't know why.

Stay tunned for updates

Any idea @sbaier1 ?

**Comment by sbaier1** [comment]
you mean it crashes at image creation?

I am seeing
```
|---------------------------Headless Information-------------------------------
|       Restart Required
|       JDownloader Updated Itself and will exit now.
|       Please restart JDownloader after a few seconds.
|       Make sure that there is no running JDownloader process before restarting.
|------------------------------------------------------------------------------
```
when running from the image on the repository.
When building locally and running the image, it is working as expected.

You should configure an automatic build at docker hub, preferrably with a trigger that fires on every JDownloader release (not sure if that is possible, maybe just use daily build) to ensure that the JDownloader installation in the image is always up to date.

**Comment by vdeville** [comment]
He crash when docker is start with image pull from docker hub
I have already make automatic build on docker hub.
I think the problem was when storage is attached to /opt/JDownloader/cfg/ i have lot of missing files

**Comment by sbaier1** [comment]
oh i somehow managed to overlook the automated build tag.

the latest build is working for me as expected, maybe you've got some corrupted config files?

**Comment by vdeville** [comment]
Hello,
Sorry for the late reply
Hummm i have test from empty volume and it's the same for me :/

**Comment by vdeville** [comment]
Need to be restart after first startup. JDownloader launch shutdown event
